// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCViurMyZ-YFFgu7K8ZPYv2iHG5dH5OdJg',
    appId: '1:740661903181:web:01b8eecc923451659fc104',
    messagingSenderId: '740661903181',
    projectId: 'freezed-app',
    authDomain: 'freezed-app.firebaseapp.com',
    storageBucket: 'freezed-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdEIEyMuBkMYaY-mQ73HuGr8-yGoKbRQ',
    appId: '1:740661903181:android:4b29ce9aacc207c49fc104',
    messagingSenderId: '740661903181',
    projectId: 'freezed-app',
    storageBucket: 'freezed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOmWRTx1A-6MBNMdbk1YyFqa0j9tYshQs',
    appId: '1:740661903181:ios:f50f99d1fa05120a9fc104',
    messagingSenderId: '740661903181',
    projectId: 'freezed-app',
    storageBucket: 'freezed-app.appspot.com',
    iosClientId: '740661903181-sns4bpdu5pe55dad5sti0uai71lhip22.apps.googleusercontent.com',
    iosBundleId: 'com.example.freezedApp',
  );
}
